### ISSUE TITLE
Breaks signed URLs in email purchase receipts

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-widgets-pack#7]
When some of these widgets are active, the signed URLs received in EDD email purchase receipts are broken. It looks to be related to the `pre_get_posts` filters in some of these widgets.

Tested with Twenty Twelve theme and Twenty Fifteen theme.

Steps to reproduce:
* Assign a widget that has a `pre_get_posts` filter, like the EDD Calendar widget.
* Make a purchase

In the email purchase receipt, the download links will be broken.

As a test to confirm my findings, comment out the `pre_get_posts` line in the widget and make another purchase. Links will work.

This does not effect EDD 2.2.8.

**Comment by pippinsplugins** [comment]
I don't understand why this happens . . . 

@cklosowski any idea?

**Comment by mindctrl** [comment]
Also affects other queries, like searches.

https://github.com/easydigitaldownloads/edd-widgets-pack/blob/master/widgets/edd-widget-downloads-calendar.php#L351-L363

**Comment by pippinsplugins** [comment]
@mindctrl Thanks! Works great!
